### ISSUE TITLE
Monthly training/forecasting test (to replicate icenet v1) 

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet-roadmap#49]
Often asked for and likely to improve the usability by proving that interfaces across the pipeline and supporting libraries are capable of dealing with different temporal domains.

This is a significant development overhead and should ensure: 

* [x] Development of the following features within the [library](https://github.com/icenet-ai/icenet)
  * https://github.com/icenet-ai/icenet/issues/21
  * https://github.com/icenet-ai/icenet/issues/22
* [x] Development of necessary commands demonstrating the functionality within the [pipeline](https://github.com/icenet-ai/icenet-pipeline)
* [x] Demonstrate with #44

**Comment by bnubald** [comment]
@JimCircadian I've set this as in progress, hope that's ok.

**Comment by JimCircadian** [comment]
Nice one @bnubald, sorry I didn't do that but I'm about 2/3 of the way through too 😆

**Comment by bnubald** [comment]
> Nice one @bnubald, sorry I didn't do that but I'm about 2/3 of the way through too 😆

Oh that's ok 😄

**Comment by JimCircadian** [comment]
Demonstrating next year forecasts based on monthly resolution 


https://github.com/user-attachments/assets/a9e9ef96-e7e9-4797-a502-9b7d628389b2
